---
name: Python Unit Tests and Linting

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8
          pip install yamllint
          sudo apt-get update && sudo apt-get install ffmpeg

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics


      - name: Ensure example file passes YAmllint
        run: |
          yamllint -fgithub -d "{rules: {line-length: false}}" podcast_config.example.yaml

      - name: Run tests
        run: |
          python -m unittest discover tests

      - name: Upload Test Feed Artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-podcast-feed
          path: test_podcast_feed_new_keys.xml
          if-no-files-found: error # Optional: error if the file isn't found
